plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

def kontaktProps = new Properties()
def localPropsFile = rootProject.file("local.properties")
if (localPropsFile.exists()) {
    kontaktProps.load(localPropsFile.newDataInputStream())
}
def kontaktApiKey = kontaktProps.getProperty("KONTAKT_API_KEY", "")

android {
    namespace = 'com.example.connectiontest'
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.connectiontest"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "KONTAKT_API_KEY", "\"${kontaktApiKey}\""
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        buildConfig = true
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation 'io.kontakt.mvn:sdk:7.2.12'
//    implementation 'com.kontaktio:sdk:7.2.12'
    
    implementation 'org.json:json:20210307'

    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.cardview
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}
